project_id = "xyhbcdlcpqbcpegkflyv"

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.zapi-instance-manager]
verify_jwt = false
